=== TSV-Willsbach/hand-website/src/assets/content/schemas/teamSchema.json
{
    "$id": "http://example.com/example.json",
    "type": "object",
    "definitions": {
        "trainer": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "prename": {
                        "type": "string"
                    },
                    "picture": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "prename"
                ]
            }
        },
        "players": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "prename": {
                        "type": "string"
                    },
                    "position": {
                        "type": "string"
                    },
                    "number": {
                        "type": "number"
                    },
                    "nickname": {
                        "type": "string"
                    },
                    "birthday": {
                        "type": "string"
                    },
                    "picture": {
                        "type": "string"
                    },
                    "joinedClub": {
                        "type": "string"
                    },
                    "lastClubs": {
                        "type": "string"

                    }
                },
                "required": [
                    "name",
                    "prename"
                ]
            }
        }
    },
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "title": {
            "$id": "/properties/title",
            "type": "string",
            "title": "The Title Schema ",
            "default": "",
            "examples": [
                "Herren"
            ]
        },
        "ligaID": {
            "$id": "/properties/ligaID",
            "type": "string",
            "title": "LigaID ",
            "default": "",
            "examples": [
                "28818"
            ]
        },
        "pokalID": {
            "$id": "/properties/pokalID",
            "type": "string",
            "title": "LigaID - Pokal",
            "default": "",
            "examples": [
                "28818"
            ]
        },
        "wpCat": {
            "$id": "/properties/wpCat",
            "type": "string",
            "title": "Wordpress Category",
            "default": "",
            "examples": [
                "20"
            ]
        },
        "picture": {
            "$id": "/properties/picture",
            "type": "string",
            "title": "The Picture Schema ",
            "default": "",
            "examples": [
                "https://wp.willsbach-handball.de/wp-content/uploads/teams/herren.jpg"
            ]
        },
        "trainer": {
            "$ref": "#/definitions/trainer"
        },
        "players": {
            "$ref": "#/definitions/players"
        }
    }
}

=== TSV-Willsbach/hand-website/src/assets/content/teams/herren.json
{
    "$schema": "../teamSchema.json",
    "title": "Herren",
    "picture": "https://wp.willsbach-handball.de/wp-content/uploads/teams/herren-768x513.jpg",
    "ligaID": "36040",
    "pokalID": "30098",
    "wpCat": "10",
    "trainer": [{
        "name": "Kohler",
        "prename": "Marco"
    }],
    "players": [{
            "position": "TW",
            "number": 12,
            "name": "Gebhardt",
            "prename": "Miguel",
            "birthday": "10.09.1992",
            "picture": "https://wp.willsbach-handball.de/wp-content/uploads/players/herren/fb_Miguel_Gebhardt_min.jpg",
            "joinedClub": "2017",
            "lastClubs": "CVJM Untertürkheim, TV Obertürkheim, HSG Oberer Neckar, TSB Horkheim"
        },
        {
            "position": "TW",
            "number": 99,
            "name": "Spannagel",
            "prename": "Daniel",
            "birthday": "14.02.1991",
            "nickname": "Spanni"
        },
        {
            "number": 11,
            "name": "Purzel",
            "prename": "Marvin",
            "birthday": "17.07.1992"
        },
        {
            "position": "Außen",
            "number": 2,
            "name": "Hohl",
            "prename": "Markus",
            "birthday": "01.10.1989"
        },
        {
            "position": "Kreis",
            "number": 4,
            "name": "Köder",
            "prename": "Simon",
            "birthday": "19.05.1990"
        },
        {
            "position": "Kreis",
            "name": "Petzold",
            "prename": "Nils",
            "birthday": "17.05.1999"
        },
        {
            "position": "Mitte",
            "number": 5,
            "name": "Busch",
            "prename": "Benedikt",
            "birthday": "08.11.1995"
        },
        {
            "name": "Galonska",
            "prename": "Tom",
            "birthday": "12.07.1999"
        },
        {
            "position": "Kreis",
            "number": 6,
            "name": "Schiedt",
            "prename": "Marvin",
            "birthday": "07.01.1995"
        },
        {
            "position": "Außen",
            "number": 7,
            "name": "Löffler",
            "prename": "Florian",
            "birthday": "13.07.1994"
        },
        {
            "position": "Kreis",
            "number": 10,
            "name": "Vetter",
            "prename": "Benjamin",
            "birthday": "14.06.1999"
        },
        {
            "number": 13,
            "name": "Rohmig",
            "prename": "Markus",
            "birthday": "08.07.1991"
        },
        {
            "position": "TW",
            "number": 25,
            "name": "Hanke",
            "prename": "David",
            "birthday": "10.11.1994"
        },
        {
            "number": 14,
            "name": "Schwidurski",
            "prename": "Silas",
            "birthday": "03.09.1998"
        },
        {
            "number": 15,
            "name": "Wörner",
            "prename": "Fabio",
            "birthday": "27.10.1999"
        },
        {
            "number": 17,
            "name": "Löffler",
            "prename": "Tim",
            "birthday": "25.11.1999"
        }

    ]
}

=== TSV-Willsbach/hand-website/src/assets/content/teams/mbjugend.json
{
    "$schema": "../teamSchema.json",
    "title": "Männliche B Jugend",
    "ligaID": "30114",
    "wpCat": "18",
    "picture": "https://wp.willsbach-handball.de/wp-content/uploads/teams/mB.jpg",
    "trainer": [{
        "name": "Bosch",
        "prename": "Heiko"
    }],
    "players": [{
            "number": 3,
            "name": "Anderl",
            "prename": "Marius"
        },
        {
            "name": "Dicht",
            "prename": "Timo"
        },
        {
            "name": "Doll",
            "prename": "Niklas"
        },
        {
            "name": "Endtner",
            "prename": "Noah"
        },
        {
            "name": "Huber",
            "prename": "Kilian"
        },
        {
            "name": "Jaspers",
            "prename": "Jann"
        },
        {
            "number": 1,
            "name": "Kral",
            "prename": "Tim"
        },
        {
            "name": "Krebs",
            "prename": "Marcel"
        },
        {
            "number": 13,
            "name": "Müller",
            "prename": "Marius"
        },
        {
            "name": "Pigan",
            "prename": "Felix"
        },
        {
            "number": 16,
            "name": "Riedel",
            "prename": "Michael"
        },
        {
            "name": "Rieker",
            "prename": "Florian"
        },
        {
            "name": "Schlestein",
            "prename": "Paul"
        },
        {
            "name": "Schwidurski",
            "prename": "David"
        },
        {
            "name": "Sommer",
            "prename": "Luis"
        },
        {
            "name": "Waldmann",
            "prename": "Nils"
        },
        {
            "name": "Wolf",
            "prename": "Alexander"
        },
        {
            "number": 12,
            "name": "Wörner",
            "prename": "Tim"
        }
    ]
}
